"""Compact, bundled emotion lexicons. No download, no secrets."""

from __future__ import annotations

EMOTIONS: dict[str, set[str]] = {
    "anger": {
        "anger",
        "angry",
        "furious",
        "rage",
        "outraged",
        "mad",
        "hate",
        "hating",
        "livid",
        "irate",
        "pissed",
        "annoyed",
        "annoyed",
        "irritating",
        "irritated",
        "stupid",
        "idiot",
        "incompetent",
        "blame",
        "blaming",
        "fed",
        "screw",
        "screwed",
        "damn",
        "dammit",
        "hell",
        "shut",
        "yelling",
        "explode",
        "explosive",
        "hostile",
        "aggression",
        "aggressive",
        "attack",
        "attacking",
        "fire",
        "fired",
        "useless",
        "pathetic",
        "ridiculous",
        "unbelievable",
        "disaster",
        "mess",
        "broken",
        "failure",
        "failing",
        "failed",
        "worst",
        "terrible",
        "awful",
        "unacceptable",
        "done",
        "quit",
        "chargeback",
        "lawsuit",
        "lawyer",
        "legal",
        "threat",
        "threatening",
        "threaten",
        "demand",
        "demanding",
    },
    "fear": {
        "afraid",
        "scared",
        "fear",
        "fearful",
        "anxious",
        "anxiety",
        "worry",
        "worried",
        "worrying",
        "panic",
        "panicking",
        "nervous",
        "uneasy",
        "dread",
        "risk",
        "risky",
        "unsafe",
        "leak",
        "leaked",
        "pii",
        "outage",
        "down",
        "crash",
        "crashing",
        "urgent",
        "emergency",
        "escalat",
        "concerned",
        "concern",
        "stress",
        "stressed",
        "overwhelmed",
        "help",
    },
    "sadness": {
        "sad",
        "sadness",
        "hurt",
        "hurting",
        "disappointed",
        "disappointing",
        "let",
        "down",
        "alone",
        "lonely",
        "tired",
        "exhausted",
        "cry",
        "crying",
        "miss",
        "missed",
        "regret",
        "sorry",
        "apology",
        "apologize",
        "heartbroken",
        "upset",
        "unhappy",
        "miserable",
        "hopeless",
        "forgotten",
        "ignored",
        "abandoned",
        "again",
    },
    "joy": {
        "happy",
        "glad",
        "joy",
        "delighted",
        "excited",
        "love",
        "loved",
        "awesome",
        "amazing",
        "wonderful",
        "great",
        "good",
        "nice",
        "yay",
        "congrats",
        "congratulations",
        "proud",
        "win",
        "winning",
        "success",
        "successful",
        "celebrate",
        "fun",
        "pleased",
        "fantastic",
        "excellent",
        "perfect",
        "brilliant",
        "cheers",
        "haha",
        "lol",
        "lmao",
    },
    "disgust": {
        "disgusting",
        "disgusted",
        "gross",
        "nasty",
        "sick",
        "revolting",
        "appalling",
        "shameful",
        "shame",
        "ew",
        "ugh",
        "trash",
        "garbage",
        "incompetent",
        "joke",
        "embarrassing",
        "embarrassed",
    },
    "trust": {
        "thanks",
        "thank",
        "thankful",
        "appreciate",
        "appreciated",
        "trust",
        "trusted",
        "reliable",
        "gotcha",
        "support",
        "supporting",
        "help",
        "helping",
        "together",
        "agree",
        "agreed",
        "lgtm",
        "solid",
        "safe",
        "please",
        "kind",
        "kindly",
    },
    "anticipation": {
        "wait",
        "waiting",
        "hope",
        "hoping",
        "soon",
        "ready",
        "plan",
        "planning",
        "upcoming",
        "later",
        "tomorrow",
        "tonight",
        "booked",
        "expect",
        "expected",
        "looking",
        "forward",
        "can't",
        "cannot",
        "demo",
        "launch",
    },
    "surprise": {
        "wow",
        "whoa",
        "unexpected",
        "shocked",
        "shocking",
        "surprised",
        "surprise",
        "unbelievable",
        "wait",
        "what",
        "seriously",
        "really",
        "huh",
        "oh",
    },
}

NEGATORS = {
    "not",
    "no",
    "never",
    "n't",
    "dont",
    "don't",
    "cannot",
    "can't",
    "hardly",
    "barely",
    "without",
    "isn't",
    "wasn't",
    "aren't",
    "weren't",
    "nope",
}

INTENSIFIERS = {
    "very": 0.35,
    "really": 0.3,
    "so": 0.25,
    "extremely": 0.45,
    "absolutely": 0.4,
    "totally": 0.35,
    "completely": 0.35,
    "literally": 0.25,
    "seriously": 0.3,
    "super": 0.3,
    "incredibly": 0.4,
    "uber": 0.3,
    "sooo": 0.4,
    "soooo": 0.45,
}

POSITIVE_SURFACE = {
    "great",
    "good",
    "nice",
    "awesome",
    "amazing",
    "perfect",
    "wonderful",
    "love",
    "loved",
    "fantastic",
    "excellent",
    "brilliant",
    "beautiful",
    "best",
    "happy",
    "glad",
    "thanks",
    "thank",
    "cool",
    "fine",
    "sure",
    "yeah",
    "yep",
    "ok",
    "okay",
    "helpful",
    "useful",
}

NEGATIVE_SURFACE = {
    "bad",
    "worst",
    "hate",
    "terrible",
    "awful",
    "horrible",
    "stupid",
    "idiot",
    "fail",
    "failed",
    "failure",
    "broken",
    "down",
    "disaster",
    "mess",
    "late",
    "forgot",
    "forget",
    "alone",
    "angry",
    "upset",
    "tired",
    "useless",
    "problem",
    "issue",
    "error",
    "outage",
    "leak",
    "lawsuit",
    "chargeback",
    "never",
    "again",
    "missed",
    "wrong",
    "risk",
    "panic",
    "yelling",
    "exploding",
    "threatening",
}

THREAT_PHRASES = (
    "i am done",
    "i'm done",
    "im done",
    "never again",
    "lawsuit",
    "call a lawyer",
    "speak to your manager",
    "chargeback",
    "chargebacks",
    "pii leaked",
    "report you",
    "report this",
    "this is a disaster",
    "i quit",
    "fire me",
    "legal just",
    "threatening",
    "not covering",
    "done covering",
    "escalate this",
    "go to legal",
    "i cannot do this again",
    "i can't do this again",
)

SARCASM_PHRASES = (
    ("yeah right", 0.72, "stock phrase"),
    ("oh great", 0.7, "stock phrase"),
    ("oh perfect", 0.7, "stock phrase"),
    ("just what i needed", 0.78, "stock phrase"),
    ("just what we needed", 0.78, "stock phrase"),
    ("love that for me", 0.74, "stock phrase"),
    ("love that", 0.45, "mock affection"),
    ("love the welcome", 0.7, "mock affection"),
    ("thanks a lot", 0.55, "thanks-as-rebuke"),
    ("thank you so much", 0.28, "overthanks"),
    ("sure, because", 0.7, "sure-because"),
    ("sure because", 0.66, "sure-because"),
    ("as if", 0.5, "as-if"),
    ("said no one ever", 0.8, "stock phrase"),
    ("wow amazing", 0.55, "inflated praise"),
    ("amazing work", 0.42, "inflated praise"),
    ("amazing timing", 0.62, "inflated praise"),
    ("nice job", 0.4, "inflated praise"),
    ("great job", 0.38, "inflated praise"),
    ("can't wait", 0.28, "can't-wait"),
    ("cannot wait", 0.28, "can't-wait"),
    ("who would have thought", 0.55, "rhetorical"),
    ("totally not", 0.6, "litotes"),
    ("not like i", 0.55, "not-like-i"),
    ("not like we", 0.55, "not-like-i"),
    ("because i definitely", 0.72, "deadpan definitely"),
    ("because we definitely", 0.72, "deadpan definitely"),
    ("whatever", 0.35, "dismissal"),
    ("sure, whatever", 0.7, "dismissal"),
    ("if you say so", 0.6, "dismissal"),
    ("good for you", 0.4, "dismissal"),
    ("must be nice", 0.58, "dismissal"),
    ("cool story", 0.62, "dismissal"),
    ("absolutely perfect", 0.4, "overpraise"),
    ("perfect. absolutely perfect", 0.75, "overpraise"),
    ("/s", 0.95, "explicit /s"),
    ("#sarcasm", 0.95, "explicit tag"),
    ("not the same thing", 0.3, "correction jab"),
    ("you're overreacting", 0.25, "dismissal"),
    ("love that we", 0.55, "mock affection"),
    ("don't bother", 0.4, "dismissal"),
    ("happy?", 0.5, "rhetorical happy"),
)

SARCASM_EMOJIS = {
    "🙄": 0.7,
    "😒": 0.65,
    "😏": 0.55,
    "🤡": 0.7,
    "🙃": 0.5,
    "😑": 0.45,
    "🤔": 0.2,
}

POSITIVE_EMOJIS = set("😀😃😄😁😊🙂🥰😍🤗🎉👍✅💚")
NEGATIVE_EMOJIS = set("😡😠🤬😢😭😞😔🙁👎💔😡")
